### PR TITLE
Snakefall Patashu Puzzle Pack 1 - 8 new snake colors, WoodPlatform, OneWayWallU/D/L/R, Foam, DiggableDirt, OpenGate, ClosedGate

### PR DESCRIPTION
**Pull request by Patashu**
The added elements in this pull request are a combination of things me and my brother Nick came up with.

---

WoodPlatform acts solid for gravity and like air otherwise.

OneWayWallU/D/L/R acts solid for any movement entering its tile through its wall, and like air otherwise.

---

Foam is like a WoodPlatform (solid to gravity, air otherwise) but if entered by anything becomes Air.

DiggableDirt is like a Fruit without the extra Fruit mechanics. Solid until entered by a snake head consciously, then becomes air.

---

After each gravity tick, if an OpenGate was occupied and now isn't, it becomes a solid ClosedGate.

(The list of occupied OpenGates is added to before and after initial movement, and after portals activate.)

This is different to the behaviour of portal activation - for example, you can push different objects past an OpenGate without it closing, and can even pull a snake tail away from an OpenGate, but have an object fall on it in the first gravity tick, without it closing. (If it takes more than one gravity tick, it will close.)

I tested all portal/block/snake interactions me and my brother Nick could think of, and they all work the way Nick wants them to.

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
wow! i can't wait to try all this. do you have some example levels i can play?

**Comment by Patashu** [comment]
I'll post any Nick makes that he's happy with here.

**Comment by thejoshwolfe** [comment]
I'm a little worried about the Open/Close Gate puzzle element. I think I was traumatized by the cheapshot level design in Chip's Challenge that abused one-way gates. For example [this level](https://www.youtube.com/watch?v=pcdMh1M7QLI#t=17m24s) which is simply a trial and error guessing game. Maybe I'm being irrational though, because in Chip's Challenge you have limited knowledge, and in Snakefall you can see everything up front. Furthermore, Snakefall has undo/redo and in Chip's Challenge you have to star the level over if you make a mistake.

Ok. I feel better now.

Regarding wooden platforms and one-way ups, I was surprised to find that I could support myself by simply occupying a space above it. I expected to need to put a horizontal surface against it. In the below image, the green snake makes sense because the tip of the tail is horizontal, but the red snake seems like it should fall. Similarly, the red block makes sense, but it seems like the pink box should fall.

screenshot_2016-08-05_11-34-59

Another concern I have is the apparent redundancy between foam and dirt and between one-way ups and wooden platforms. I had read your explanations, but I struggled to remember the distinction just now, and it took a surprisingly long time to discover the difference by playing around with it. This isn't necessarily a problem, but I wanted to give some feedback on my first impressions. I can definitely imagine people will ask themselves "was it dirt or foam that i can push blocks through?" even after they've seen the answer several times. By contrast, no one will ask "was it fruit or teleporters that I need to eat to win the game?". The original game as simple enough that you would never forget the game's programming once you'd seen it (well, except that the way teleporters work is really weird). Again, not necessarily anything wrong with your ideas. Just wanted to describe how more complexity can be frustrating for some people.

I guess this discussion is circling around the question of why did you make this pull request? Probably an easy question to answer, but my assumption is that the answer would be "to make a good game". However, it might be "because I want to have fun". And it's probably not "to make money selling the game". So all of those reasons have a different purpose and even slightly different target audiences, which will influence what kinds of things go into the game. For example, if you were trying to make a good game, then a sequence of levels that introduce game mechanics one at a time would be important, but if your goal is to have fun, then the [wiki list of levels](https://github.com/thejoshwolfe/snakefall/wiki) is a satisfactory way to manage levels you make.

Anyway, really cool additions you've made! I look forward to trying some levels you throw at me. In the meantime, here's a level I made with the mechanics in f828a71fc35efea312035b167add3f5f538f70f4.

```
3tFRIoTU&11&11?*810:01110901101*1010113<*10;3*11666*11*007*0011*501100*170011*004*0011*52*81/b0?36&40/s0?69&68&79/s1?73&74&85/
```

**Comment by Patashu** [comment]
Hanging on to wooden platforms without a horizontal surface: The way I rationalize wooden platforms as working is like thin platforms in other platformers - where you hold down and jump to pass through them (like Terraria and Starbound). In that sense, red hanging on with his tail makes sense - since you can move downwards through a platform, it implies that he's just hanging off of the 'side', into the screen or out of the screen. But I agree that the pink block's position doesn't make logical sense, since you don't think of a block as 'bending' around a platform.

I think the distinction between foam and diggable dirt is okay. Foam is depicted as looking very frail whereas diggable dirt looks solid. Though it would be good if diggable dirt's graphic looked more 'diggable', though I'm not sure how to do that atm.

I definitely agree that there are issues with the current implementation + depiction of wooden platforms though. There should be a way it can be changed to be more intuitive.

And I definitely agree overall that too much complexity can turn players off of your game. Snakebird has the advantage that it introduces you to elements and concepts one by one, Snakefall does not have such a thing. Possible solutions (pick one or more): Hiding advanced elements in the editor behind a collapsible section, having an hourglass that you can hold over an element to discover how it works, having a guide to Snakefall elements and mechanics at the bottom of the Snakefall page, having one or more tutorial levels that teaches you how everything works as you start up the game. (Also, taking the level list from the wiki and integrating it into the Snakefall page itself somehow seems good, probably sorting by difficulty/fun/complexity in some way - people who stumble upon the game won't have to leave the page to find levels to try.)

The pull request I suppose is exploratory - to probe the question 'what kinds of puzzles can we make if we don't restrict ourselves to just elements that appear in Snakebird'. As such, not every element brought up while answering such a question may be worth including in Snakefall.

Snakebird is intriguing in that every element of the game is extremely tightly bound - walls, air, snakes, blocks, spikes, fruit, exits and portals are all extremely intuitive and in general implemented in the way you'd expect them to be, and yet all of them have an extremely high potential for creating puzzles. (Yes, I even include portals here. You bag on them a lot, but I feel like every decision made related to them is the cleaner choice. For example, if a portal could transport a snake even if the snake was still inside of it, it implies that the portal could also transport a snake that made absolutely no movement - which would imply an infinite loop could happen of a stationary snake transporting back and forth. Requiring a condition like leaving and re-entering cleanly ensures no such infinite loops.)

So we want to discover and add to Snakefall elements like those - that are easy to reason about, fit well into the model of Snakebird and allow for a wide variety of puzzles to be created. While I started with just simple elements, I have lots of ideas for more complex ones - lasers that kill snakes but are blocked by blocks, conveyor belts that shift everything on them once a turn, switches that control the prior elements, attaching spikes and fruit and diggable dirt to blocks, balloons that act like anti-gravity blocks and so on. I'm sure you have your own ideas, since you've mentioned keys and doors before. Without trying things to see how good they are for making puzzles, we can't know what's the most exciting to include.

When I get home, I'll bring this up with Nick (my brother, who's way better at puzzles than me but doesn't code, hence the current arrangement LOL) and we'll go over your level and this conversation.

**Comment by thejoshwolfe** [comment]
I updated the link in the above comment and actually loaded this code there. However, I can't link to the level I made because the `<` character gets %-escaped and the level deserializer doesn't know how to deal with that. I'm inclined to think we should just use a different character for serialization. I'd like to keep snakefall links friendly to naive url linkifier regexes, which means no spaces, no `.`, no `)`, etc.

**Comment by Patashu** [comment]
Sure thing. I didn't think about that as a possible problem.

**Comment by thejoshwolfe** [comment]
Alright. I updated the link again, and now the main page of the game has a link to a list of experimental versions, which is currently just this one.

**Comment by thejoshwolfe** [comment]
I'm going to make some edits to your code in my branch called `patashu-puzzle-pack-1`, such as changing the serialization characters to be more link friendly. I think there's some way for you to set up your fork to follow a particular branch of my fork, but I'm not clear on all the details. Anyway, thought I should keep you updated on what i'm doing.

**Comment by Patashu** [comment]
OK, sounds good. (Apologies on my end, Nick hasn't been in a Snakefall mood lately, and I've been tired as hecko anyway)

**Comment by thejoshwolfe** [comment]
Alright finally. Here's a link to the level I made:

http://wolfesoftware.com/snakefall/experimental/patashu-puzzle-pack-1/#level=3tFRIoTU&11&11?*810r01110l01101*1010113t*10f3*11www*11*00u*0011*501100*1u0011*004*0011*52*81/s0?69&68&79/s1?73&74&85/b0?36&40/

**Comment by thejoshwolfe** [comment]
I refactored master quite a bit, and I'm afraid this branch might need quite a bit of rework to merge cleanly. In the meantime, I've begun implementing some experimental ideas myself, starting with my idea for platforms here. [Here's an example level that uses platforms the way i imagine them](http://wolfesoftware.com/snakefall/experimental/patashu-remix-1/#level=HyRr4JK1&18&16?04*l06*B06*F0*02*306*00*012*5060*11200066*40111*506022111*106*501*606*001*20101*201*10100*41*30*41*001*00*21*10*2100111*20*01*0011000/s0?114&113&129/b0?187&188&139/).

**Comment by Patashu** [comment]
Oh cool! joshwolfe style platforms :D

**Comment by XeroOl** [comment]
[Under Cover](http://wolfesoftware.com/snakefall/experimental/patashu-remix-1/#level=HyRr4JK1&11&14?001*80111*701*K02*5016161000*2604101*302011101*002001*101200210012120111001100*0121*001*001*20/s0?34&35&36&37&38/s4?48&49&50&51&52/f0?78/f1?81/) by [XeroOl](https://github.com/XeroOl)
Where should I post levels with these experimental mechanics?

**Comment by thejoshwolfe** [comment]
Brilliant! I can't solve that level. It's great to have you contributing to the community XeroOl!

I've made an "Experimental" wiki page and published your level there: https://github.com/thejoshwolfe/snakefall/wiki/Experimental

**Comment by XeroOl** [comment]
Uh oh! I realized that I can't solve it either.
I thought I removed the ceiling before posting it, but I guess I forgot to save... 
I'll change it to be possible.
Sorry XD

**Comment by Patashu** [comment]
Just putting this here so I don't forget:

http://www.draknek.org/games/puzzlescript/boxing-gloves.php

Being able to attach boxing gloves to blocks (like in this Puzzlescript game) could make for a good puzzle element. Though with gravity existing in this game and not in that one, I'm not sure. Though TBH, there's no reason why you couldn't HAVE blocks that ignore gravity, or even experience reverse gravity, and they'd probably be interesting puzzle elements in their own right (not to mention combined with gimmicks like this).

**Comment by thejoshwolfe** [comment]
Alright everyone. I've opened some specific-topic idea threads. (see above "referenced" notifications.)

There's a page on the wiki to post levels that use experimental mechanics.

The state of this pull request is that it's in a branch called [patashu-puzzle-pack-1](https://github.com/thejoshwolfe/snakefall/tree/patashu-puzzle-pack-1) and an experimental version is published at [patashu-puzzle-pack-1](http://wolfesoftware.com/snakefall/experimental/patashu-puzzle-pack-1/). This branch has diverged from master quite a bit, so I will not be merging in the latest code to keep this branch up to date; in other words, this branch is a dead end. However, the code in this pull request will probably remain available for experimentation forever at the links mentioned in this paragraph.

I'm closing this pull request, and I recommend discussion move into relevant subtopics above just for the sake of organization.

A big thanks to everyone in the community for contributing!

**Pull request closed without merging**
