### PR TITLE
Transparent Green boxes

### PR DESCRIPTION
**Pull request by XeroOl**
you might want to change the BlockBackground colors to be darker, but this should be good

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
> This branch has conflicts that must be resolved

Do you know how to resolve that problem?

**Comment by XeroOl** [comment]
idk how to fix it, should I re-code it?

**Comment by XeroOl** [comment]
https://github.com/thejoshwolfe/snakefall/network

**Comment by thejoshwolfe** [comment]
ok, that message I quoted looks like it might be visible to me only; sorry. The problem is that your pull request is a modification of old code as shown in the network graph you linked. This happened because I was writing and pushing code to master while you were making the pull request. You can resolve this on your end by rebasing onto my new master or by merging my new master into your code.

I'm still working on #9 now, but in order to avoid clashing on master again, I'll switch to a branch. I won't change my master for a while so you don't have to worry about us racing against one another for the moment. Once your pull request is merged, I'll merge my new changes with yours, and we'll all be back on the same page again.

**Comment by andrewrk** [comment]
screenshot - 08312015 - 10 39 50 am

it's visible to everybody. you can test this by visiting the page in porn mode.

**Comment by andrewrk** [comment]
oops, I was wrong about porn mode. But I'm fairly certain that what I see is the same as what you see, @XeroOl

**Comment by XeroOl** [comment]
well I still don't know if I should re-code it.

**Comment by XeroOl** [comment]
Ok i fixed the merge but it won't let me make more pull requests. Close this one so I can add another one.

**Comment by XeroOl** [comment]
Oh I can close it

**Comment by XeroOl** [comment]
See #23 for the new pull request

**Pull request closed without merging**
