### PR TITLE
Added Coloring for Blocks

### PR DESCRIPTION
**Pull request by XeroOl**
There are now 5 different block color sets which range from red to
purple to blue.

### CODE REVIEW

**Comment by XeroOl** [comment]
this should make solve #20.

**Comment by thejoshwolfe** [comment]
I've got some stuff I need to attend to today. I'll check this out tomorrow.

**Comment by XeroOl** [comment]
I also have one with transparent blocks on my repository, but I can't make more pull requests with this one pending.

**Comment by thejoshwolfe** [comment]
btw, you can make multiple pull requests at once if you use different branches. Github pull requests follow the HEAD of a branch, so if you have separate branches, you can have separate pull requests.

that being said, it's kind of a pain to make your changes independently of one another instead of making your changes in historical sequence.

The transparent centers look good. I look forward to another pull request.

**Pull request merged**
